import type { Metadata } from "next";
import "../styles/globals.css";
import { TripProvider } from "@/contexts/tripStore";
import 'flowbite';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <TripProvider>{children}</TripProvider>
      </body>
    </html>
  );
}
